Split `wekeo` provider
CS-SI/eodag pull request #1214
Opened 2024-06-14 14:23 UTC by anesson-cs

Split `wekeo` provider into `wekeo_sentinel` and `wekeo_ecmwf` to separate Sentinel and ECMWF data which are queried differently and that have two different way to discover their product types queryables

2024-07-24 06:46 UTC, dalpasso approved these changes

2024-08-08 15:42 UTC, sbrunato requested changes

2024-08-08 15:42 UTC, sbrunato commented on eodag/plugins/search/qssearch.py
> +    """A specialisation of a QueryStringSearch that uses generic STAC configuration"""
```suggestion
    """A specialisation of a :class:`~eodag.plugins.search.qssearch.PostJsonSearch` that
    uses generic STAC configuration for queryables.
    """
```

2024-08-08 15:42 UTC, sbrunato commented on eodag/plugins/search/qssearch.py
> +                f"Cannot fetch general queryables with {self.provider}. A product type must be specified"
```suggestion
                f"Cannot fetch global queryables with {self.provider}. A product type must be specified"
```

2024-08-08 15:42 UTC, sbrunato commented on tests/units/test_search_plugins.py
> +        mock_query_string_stacsearch,
```suggestion
        mock_build_qs_postjsonsearch,
        mock_build_qs_stacsearch,
```

2024-08-08 15:42 UTC, sbrunato commented on tests/units/test_search_plugins.py
> +            mock_query_string_stacsearch.return_value
```suggestion
        mock_build_qs_postjsonsearch.return_value = (
            mock_build_qs_stacsearch.return_value
```

2024-08-08 15:42 UTC, sbrunato commented on tests/units/test_search_plugins.py
> +        mock_query_string_stacsearch.assert_not_called()
```suggestion
        mock_build_qs_postjsonsearch.assert_called()
        mock_build_qs_stacsearch.assert_not_called()
```

2024-08-08 15:50 UTC, sbrunato requested changes

2024-08-08 15:50 UTC, sbrunato commented on docs/plugins.rst
> +| wekeo_main          | PostJsonSearchWithStacQueryables | TokenAuth                     | HTTPDownload   |
```suggestion
| wekeo_main         | PostJsonSearchWithStacQueryables | TokenAuth                     | HTTPDownload   |
```

2024-08-09 07:24 UTC, sbrunato approved these changes

2024-08-09 07:32 UTC, merged