Wip server errors
CS-SI/eodag pull request #1237
Opened 2024-06-25 10:45 UTC by alambare

### Your checklist for this pull request
Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

### Description
Please describe your pull request.

### Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Thank you!

2024-07-10 15:52 UTC, sbrunato submitted a review, later dismissed
rebase needed

2024-07-26 12:59 UTC, dalpasso commented
Please rebase

2024-08-07 13:35 UTC, dalpasso requested changes
- The messages should be formatted without the colon and with a uppercase `M`:

https://github.com/CS-SI/eodag/blob/63b59837952e25594e11f039b5a5d77cd84f885b/eodag/plugins/authentication/generic.py#L50-L53

Like this:
```python
raise MisconfiguredError(
    f"Cannot authenticate with {self.provider}",
    f"Method {method} is not supported. Must be one of digest or basic",
)
```
- Exception message should be exploded in a similar way to other `AuthenticationError`.

https://github.com/CS-SI/eodag/blob/63b59837952e25594e11f039b5a5d77cd84f885b/eodag/plugins/authentication/openid_connect.py#L142-L145

Like this:
```python
raise AuthenticationError(
    f"Please check your credentials for {self.provider}",
    f"HTTP Error {e.response.status_code} returned",
    response_text,
)
```
- Exception message should be exploded in a similar way to other `AuthenticationError`.

https://github.com/CS-SI/eodag/blob/63b59837952e25594e11f039b5a5d77cd84f885b/eodag/plugins/download/s3rest.py#L191-L197

 Like this:

```python
raise AuthenticationError(
    f"Please check your credentials for {self.provider}",
    f"HTTP Error {err.response.status_code} returned",
    err.response.text.strip(),
)
```
- Exception message should be exploded in a similar way to other `AuthenticationError`.

https://github.com/CS-SI/eodag/blob/fad1677fa5ad1f44536e5fdb80a44aa09afdd744/eodag/plugins/download/aws.py#L620-L627

Like this:
```python
raise AuthenticationError(
    f"Please check your credentials for {self.provider}",
    f"HTTP Error {err["Code"]} returned",
    err["Message"],
)
```
- Exception message should be exploded in a similar way to other `AuthenticationError`.

https://github.com/CS-SI/eodag/blob/fad1677fa5ad1f44536e5fdb80a44aa09afdd744/eodag/plugins/download/http.py#L839-L846

Like this:
```python
raise AuthenticationError(
    f"Please check your credentials for {self.provider}",
    f"HTTP Error {e.response.status_code} returned",
    response_text,
)
```
- Exception message should be exploded in a similar way to other `AuthenticationError`.

https://github.com/CS-SI/eodag/blob/fad1677fa5ad1f44536e5fdb80a44aa09afdd744/eodag/plugins/download/http.py#L1250-L1257

Like this:
```python
raise AuthenticationError(
    f"Please check your credentials for {self.provider}",
    f"HTTP Error {e.response.status_code} returned",
    e.response.text.strip(),
)
```

2024-08-09 10:15 UTC, alambare commented on eodag/plugins/search/qssearch.py
>                  )
changes done

2024-08-09 11:50 UTC, dalpasso approved these changes

2024-09-12 13:01 UTC, sbrunato requested changes

2024-09-12 13:01 UTC, sbrunato commented on eodag/rest/errors.py
missing tests (actual coverage = 56%)

2024-09-17 13:32 UTC, dalpasso commented on eodag/rest/errors.py
Test has been added. A single case in `errors.py` was left out to avoid further delay (see TODO in the comment).

2024-09-19 09:28 UTC, sbrunato requested changes

2024-09-19 09:28 UTC, sbrunato commented on eodag/rest/errors.py
> +                or 500
Incompatible types in assignment (expression has type "int", target has type "str")mypy[assignment](https://mypy.readthedocs.io/en/stable/_refs.html#code-assignment)

2024-09-19 09:28 UTC, sbrunato commented on eodag/rest/errors.py
> +                    exception.message = exception.message.replace(
"Exception" has no attribute "message"mypy[attr-defined](https://mypy.readthedocs.io/en/stable/_refs.html#code-attr-defined)

2024-09-19 09:28 UTC, sbrunato commented on eodag/rest/errors.py
> +                error_dict["message"] = exception.message
"Exception" has no attribute "message"mypy[attr-defined](https://mypy.readthedocs.io/en/stable/_refs.html#code-attr-defined)

2024-09-19 09:28 UTC, sbrunato commented on eodag/rest/errors.py
> +            error_list.append(error_dict)
Argument 1 to "append" of "list" has incompatible type "dict[str, str]"; expected "dict[str, str | int]"mypy[arg-type](https://mypy.readthedocs.io/en/stable/_refs.html#code-arg-type)

2024-09-19 09:28 UTC, sbrunato commented on eodag/rest/errors.py
> +            return self.errors[0]["status_code"]
Incompatible return value type (got "str | int", expected "int")mypy[return-value](https://mypy.readthedocs.io/en/stable/_refs.html#code-return-value)

2024-09-19 09:28 UTC, sbrunato commented on eodag/rest/errors.py
> +            exc.message = exc.message.replace(error_param, stac_param)
"EodagError" has no attribute "message"mypy[attr-defined](https://mypy.readthedocs.io/en/stable/_refs.html#code-attr-defined)

2024-09-19 09:28 UTC, sbrunato commented on eodag/rest/errors.py
> +        detail = exc.message
"EodagError" has no attribute "message"mypy[attr-defined](https://mypy.readthedocs.io/en/stable/_refs.html#code-attr-defined)

2024-09-19 09:28 UTC, sbrunato commented on eodag/rest/errors.py
> +        status_code=error.status_code,
"Exception" has no attribute "status_code"mypy[attr-defined](https://mypy.readthedocs.io/en/stable/_refs.html#code-attr-defined)

2024-09-19 09:28 UTC, sbrunato commented on eodag/rest/errors.py
> +    app.add_exception_handler(RequestError, eodag_errors_handler)
Argument 2 to "add_exception_handler" of "Starlette" has incompatible type "Callable[[Request, EodagError], Coroutine[Any, Any, ORJSONResponse]]"; expected "Callable[[Request, Exception], Response | Awaitable[Response]] | Callable[[WebSocket, Exception], Awaitable[None]]"mypy[arg-type](https://mypy.readthedocs.io/en/stable/_refs.html#code-arg-type)

2024-09-19 09:28 UTC, sbrunato commented on eodag/rest/errors.py
> +        app.add_exception_handler(exc, eodag_errors_handler)
Argument 2 to "add_exception_handler" of "Starlette" has incompatible type "Callable[[Request, EodagError], Coroutine[Any, Any, ORJSONResponse]]"; expected "Callable[[Request, Exception], Response | Awaitable[Response]] | Callable[[WebSocket, Exception], Awaitable[None]]"mypy[arg-type](https://mypy.readthedocs.io/en/stable/_refs.html#code-arg-type)

2024-09-19 09:28 UTC, sbrunato commented on eodag/rest/errors.py
> +    app.add_exception_handler(ResponseSearchError, response_search_error_handler)
Argument 2 to "add_exception_handler" of "Starlette" has incompatible type "Callable[[Request, ResponseSearchError], Coroutine[Any, Any, ORJSONResponse]]"; expected "Callable[[Request, Exception], Response | Awaitable[Response]] | Callable[[WebSocket, Exception], Awaitable[None]]"mypy[arg-type](https://mypy.readthedocs.io/en/stable/_refs.html#code-arg-type)

2024-09-19 09:28 UTC, sbrunato commented on tests/units/test_http_server.py
> +        # TODO add test for an exception with `parameters` attribute
Please add the missing test in this PR

2024-09-23 16:21 UTC, sbrunato approved these changes

2024-09-23 16:23 UTC, merged