fix: invalid characters in download urls
CS-SI/eodag pull request #1276
Opened 2024-07-26 07:03 UTC by jlahovnik

the path part of the "href" values of the assets is now quoted to avoid invalid characters in the urls (e.g. due to commas in the id)
solves [gitlab issue](https://gitlab.si.c-s.fr/dedl/tasks/-/issues/54)

2024-07-29 07:14 UTC, dalpasso requested changes
The path should be quoted also in the `links` section of the item:


```json
  "links": [
	{
	  "rel": "self",
	  "title": "W_XX-EUMETSAT-Darmstadt,HYPERSPECT+SOUNDING,METOPA+PW3+IASI_C_EUMP_20070710090558Z_20070710104454Z_eps_r_l2_0101",
	  "href": "http://localhost:5000/collections/METOP_IASTHR011/items/W_XX-EUMETSAT-Darmstadt,HYPERSPECT+SOUNDING,METOPA+PW3+IASI_C_EUMP_20070710090558Z_20070710104454Z_eps_r_l2_0101"
	},
	{
	  "rel": "root",
	  "href": "http://localhost:5000/"
	},
	{
	  "rel": "parent",
	  "title": "METOP_IASTHR011",
	  "href": "http://localhost:5000/collections/METOP_IASTHR011"
	},
	{
	  "rel": "collection",
	  "title": "METOP_IASTHR011",
	  "href": "http://localhost:5000/collections/METOP_IASTHR011"
	}
  ],

2024-07-29 09:01 UTC, jlahovnik commented
> The path should be quoted also in the `links` section of the item:
> 
> ```json
>   "links": [
> 	{
> 	  "rel": "self",
> 	  "title": "W_XX-EUMETSAT-Darmstadt,HYPERSPECT+SOUNDING,METOPA+PW3+IASI_C_EUMP_20070710090558Z_20070710104454Z_eps_r_l2_0101",
> 	  "href": "http://localhost:5000/collections/METOP_IASTHR011/items/W_XX-EUMETSAT-Darmstadt,HYPERSPECT+SOUNDING,METOPA+PW3+IASI_C_EUMP_20070710090558Z_20070710104454Z_eps_r_l2_0101"
> 	},
> 	{
> 	  "rel": "root",
> 	  "href": "http://localhost:5000/"
> 	},
> 	{
> 	  "rel": "parent",
> 	  "title": "METOP_IASTHR011",
> 	  "href": "http://localhost:5000/collections/METOP_IASTHR011"
> 	},
> 	{
> 	  "rel": "collection",
> 	  "title": "METOP_IASTHR011",
> 	  "href": "http://localhost:5000/collections/METOP_IASTHR011"
> 	}
>   ],
> ```

urls in links are now also quoted

2024-07-29 11:03 UTC, dalpasso approved these changes

2024-08-09 13:32 UTC, sbrunato approved these changes

2024-08-09 13:33 UTC, merged