fix: change child links at stac catalog root
CS-SI/eodag pull request #1306
Opened 2024-08-27 15:06 UTC by jlahovnik

change path of child links at STAC API root endpoint from catalogs to collections

2024-08-28 12:31 UTC, dalpasso approved these changes

2024-09-13 10:00 UTC, sbrunato submitted a review, later dismissed
Please
- [x] do not list `/catalogs/*` or `/collections/*` in landing page
- [x] remove `/catalogs` feature from `eodag/resources/stac.yml` and `eodag/rest/stac.py`
- [x] update documentation

2024-09-16 15:00 UTC, jlahovnik commented
> Please
> 
>     * [x]  do not list `/catalogs/*` or `/collections/*` in landing page
> 
>     * [x]  remove `/catalogs` feature from `eodag/resources/stac.yml` and `eodag/rest/stac.py`
> 
>     * [x]  update documentation

catalogs endpoints and correspoding logic removed

2024-09-17 15:03 UTC, dalpasso requested changes
1. Update/remove reference to `catalogs`:

https://github.com/CS-SI/eodag/blob/fdf0f1b14c367c8dcf4ce456d43114549eae0448/README.rst?plain=1#L177-L188

2. Update URLs to use `collections` instead of `catalogs`:

https://github.com/CS-SI/eodag/blob/fdf0f1b14c367c8dcf4ce456d43114549eae0448/docs/stac_rest.rst?plain=1#L113-L124

3. Probably this could be removed:

https://github.com/CS-SI/eodag/blob/fdf0f1b14c367c8dcf4ce456d43114549eae0448/eodag/rest/constants.py#L27

4. Parameters `catalogs` should be changed to `collection` or `collection_id`:

https://github.com/CS-SI/eodag/blob/fdf0f1b14c367c8dcf4ce456d43114549eae0448/eodag/rest/core.py#L234-L241

5. Update documentation:

https://github.com/CS-SI/eodag/blob/fdf0f1b14c367c8dcf4ce456d43114549eae0448/eodag/rest/stac.py#L871

2024-09-18 07:50 UTC, jlahovnik commented
catalogs removed from download and download docs

2024-09-18 08:40 UTC, dalpasso approved these changes

2024-09-19 12:34 UTC, sbrunato submitted a review, later dismissed

2024-09-19 14:18 UTC, jlahovnik commented on docs/stac_rest.rst
> -
STAC Browser section re-added

2024-09-23 15:57 UTC, sbrunato requested changes
browsing by catalog still appears in`README`, image https://raw.githubusercontent.com/CS-SI/eodag/develop/docs/_static/stac_browser_example_600.png.
Please:
- remove this image (resized and full)
- replace this outdated image and `stac_browser_start.png` with an nicer one (full and resized), similar to `stac_browser_example.png` (using a search)

2024-09-24 13:06 UTC, sbrunato requested changes

2024-09-24 13:06 UTC, sbrunato commented on docs/_static/stac_browser_start.png
should be deleted

2024-09-24 13:10 UTC, sbrunato approved these changes

2024-09-24 13:11 UTC, merged