Add mapping for parameter `hydrological_year` to provider `wekeo_ecmwf`
CS-SI/eodag pull request #1313
Opened 2024-09-05 09:25 UTC by dalpasso

Add mapping for parameter `hydrological_year` to provider `wekeo_ecmwf`.

This fix adds the parameter `hydrological_year` to `_dc_qs` of the `downloadLink` in the returned item.

2024-09-05 09:39 UTC, alambare approved these changes

2024-09-05 09:41 UTC, alambare requested changes
It is normal that the format of the parameter is different than the other configured for provider wekeo ? 

For instance with `statistic`:

```yaml
    statistic:
        - '{{"statistic": {statistic}}}'
        - '$.null'
```

2024-09-05 10:21 UTC, dalpasso commented
> It is normal that the format of the parameter is different than the other configured for provider wekeo ?
> 
> For instance with `statistic`:
> 
> ```yaml
>     statistic:
>         - '{{"statistic": {statistic}}}'
>         - '$.null'
> ```

I used he same format of `hydrological_model` but it's indeed better to use the same format as other `wekeo` parameter. I have changed the format and tested that the resulting behavior is the same.

2024-09-12 09:45 UTC, jlahovnik approved these changes

2024-09-13 07:47 UTC, sbrunato approved these changes

2024-09-13 08:41 UTC, sbrunato approved these changes

2024-09-13 08:43 UTC, merged