fix(plugins): better error handling for cop_marine
CS-SI/eodag pull request #1336
Opened 2024-10-08 09:30 UTC by jlahovnik

improves the error handling at the request to fetch the product type information in `CopMarineSearch`:
- only use `UnsupportedProductType` exception in case of `NotFound` error code
- otherwise `RequestError` will be raised

2024-10-11 13:57 UTC, sbrunato requested changes

2024-10-11 13:57 UTC, sbrunato commented on eodag/plugins/search/cop_marine.py
> +            raise
better use `eodag.exceptions.RequestError`

2024-10-14 10:40 UTC, jlahovnik commented on eodag/plugins/search/cop_marine.py
> +            raise
changed

2024-10-15 08:48 UTC, sbrunato submitted a review, later dismissed

2024-10-22 14:09 UTC, sbrunato approved these changes

2024-10-22 14:10 UTC, merged