1352 add dedicated liveness endpoint
CS-SI/eodag pull request #1353
Opened 2024-10-17 09:58 UTC by amarandon

At the moment we query / to ensure that the rest api is alive. This results in a lot of requests which can't be filtered out from the logs because we want to log requests to / coming from real users.

- [ ] add endpoint to rest API
- [ ] Modify the EO Catalogue Helm chart to use the proper endpoint to check the liveness/readiness of the STAC API component: /_mgmt/ping

2024-10-17 10:27 UTC, jlahovnik approved these changes

2024-10-28 10:02 UTC, amarandon commented
@jlahovnik I added a commit which filters out the message referring to the liveness endpoint from the logs

2024-11-21 15:04 UTC, sbrunato requested changes

2024-11-21 15:04 UTC, sbrunato commented on eodag/utils/__init__.py
> +
please move to `eodag/rest/utils/__init__.py`

2024-11-21 16:22 UTC, sbrunato approved these changes

2024-11-21 16:23 UTC, merged