fix: search and download with creodias_s3 for products without assets
CS-SI/eodag pull request #1425
Opened 2024-12-02 17:00 UTC by jlahovnik

If a product from creodias_s3 was stored on the s3 in a .tar file with the path bucket/../product_id.tar instead of having the structure bucket/../product_id/asset, the search for a request for which the response includes such a product was failing.

The creodias search and the download plugin have now been adapted to consider this case.

2024-12-04 15:14 UTC, sbrunato requested changes

2024-12-04 15:31 UTC, jlahovnik commented on eodag/plugins/download/creodias_s3.py
> +        :param product: product for which the assets shall be downloaded
changed

2024-12-04 15:32 UTC, jlahovnik commented on tests/units/test_download_plugins.py
> +    def test_plugins_download_creodias_s3_withou_assets(
changed

2025-01-03 10:31 UTC, sbrunato approved these changes

2025-01-03 10:37 UTC, merged