refactor(ecmwf): simplify ECMWFSearch configuration
CS-SI/eodag pull request #1433
Opened 2024-12-09 08:38 UTC by alambare

This PR simplifies the configuration of `ECMWFSearch` products. 

- metadata mapping defined in the plugin are extended to cover all the common metadata mapping across `ECMWFSearch` providers
- remove the need of `"ecmwf:"` prefix in products configuration
- update config to always get datetime parameters from `datetime` filter in addition to ecmwf `day`, `month`, `year`
- change the date interval in case of missing end to be `start/start` instead of `start/start + 1d`. This is done to align the behavior of EODAG with the way ECMWF expects.

2025-02-07 17:32 UTC, jlahovnik submitted a review, later dismissed
I tried to do a download but I git an error when I clicked on the downloadLink.

`
2025-02-07 18:30:45,072 uvicorn.error                    [ERROR   ] Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 178, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 767, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 177, in __call__
    |     with recv_stream, send_stream, collapse_excgroups():
    |   File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 179, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/eodag/rest/server.py", line 211, in forward_middleware
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 154, in call_next
    |     raise app_exc
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 141, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    |     await self.app(scope, receive, send)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    |     return await run_in_threadpool(dependant.call, **values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2461, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 962, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/eodag/rest/server.py", line 266, in stac_collections_item_download
    |     return download_stac_item(
    |            ^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/eodag/rest/core.py", line 268, in download_stac_item
    |     download_stream = product.downloader._stream_download_dict(
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/eodag/plugins/download/http.py", line 797, in _stream_download_dict
    |     chunk_iterator = self._stream_download(
    |                      ^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/eodag/plugins/download/http.py", line 965, in _stream_download
    |     self.stream = s.request(
    |                   ^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    |     prep = self.prepare_request(req)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    |     p.prepare(
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/requests/models.py", line 367, in prepare
    |     self.prepare_url(url, params)
    |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/requests/models.py", line 438, in prepare_url
    |     raise MissingSchema(
    | requests.exceptions.MissingSchema: Invalid UR [...]

2025-02-07 17:32 UTC, jlahovnik commented on eodag/resources/providers.yml
>          <<: *day_month_year
I don't know if this is a recent change or if we got it wrong previously but there is no day but a nominal_day parameter (only value possible for our selected version "01").

2025-02-10 10:53 UTC, alambare commented on eodag/resources/providers.yml
>          <<: *day_month_year
Corrected to map day from datetime parameters to `nominal_day`.

2025-02-10 10:55 UTC, alambare commented
> I tried to do a download but I git an error when I clicked on the downloadLink.
> 
> ` 2025-02-07 18:30:45,072 uvicorn.error [ERROR ] Exception in ASGI application
> 
> * Exception Group Traceback (most recent call last):
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_utils.py", line 76, in collapse_excgroups
>   |     yield
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 178, in **call**
>   |     async with anyio.create_task_group() as task_group:
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 767, in **aexit**
>   |     raise BaseExceptionGroup(
>   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
>   +-+---------------- 1 ----------------
>   | Traceback (most recent call last):
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
>   |     result = await app(  # type: ignore[func-returns-value]
>   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in **call**
>   |     return await self.app(scope, receive, send)
>   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in **call**
>   |     await super().**call**(scope, receive, send)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/applications.py", line 112, in **call**
>   |     await self.middleware_stack(scope, receive, send)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in **call**
>   |     raise exc
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in **call**
>   |     await self.app(scope, receive, _send)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 177, in **call**
>   |     with recv_stream, send_stream, collapse_excgroups():
>   |   File "/usr/lib/python3.11/contextlib.py", line 155, in **exit**
>   |     self.gen.throw(typ, value, traceback)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
>   |     raise exc
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 179, in **call**
>   |     response = await self.dispatch_func(request, call_next)
>   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/eodag/rest/server.py", line 211, in forward_middleware
>   |     response = await call_next(request)
>   |                ^^^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 154, in call_next
>   |     raise app_exc
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 141, in coro
>   |     await self.app(scope, receive_or_disconnect, send_no_error)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in **call**
>   |     await self.app(scope, receive, send)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in **call**
>   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>   |     raise exc
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
>   |     await app(scope, receive, sender)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/routing.py", line 715, in **call**
>   |     await self.middleware_stack(scope, receive, send)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
>   |     await route.handle(scope, receive, send)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
>   |     await self.app(scope, receive, send)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
>   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>   |     raise exc
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
>   |     await app(scope, receive, sender)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
>   |     response = await f(request)
>   |                ^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
>   |     raw_response = await run_endpoint_function(
>   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
>   |     return await run_in_threadpool(dependant.call, **values)
>   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
>   |     return await anyio.to_thread.run_sync(func)
>   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
>   |     return await get_async_backend().run_sync_in_worker_thread(
>   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2461, in run_sync_in_worker_thread
>   |     return await future
>   |            ^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 962, in run
>   |     result = context.run(func, *args)
>   |              ^^^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/eodag/rest/server.py", line 266, in stac_collections_item_download
>   |     return download_stac_item(
>   |            ^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/eodag/rest/core.py", line 268, in download_stac_item
>   |     download_stream = product.downloader._stream_download_dict(
>   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/eodag/plugins/download/http.py", line 797, in _stream_download_dict
>   |     chunk_iterator = self._stream_download(
>   |                      ^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/eodag/plugins/download/http.py", line 965, in _stream_download
>   |     self.stream = s.request(
>   |                   ^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
>   |     prep = self.prepare_request(req)
>   |            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
>   |     p.prepare(
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/requests/models.py", line 367, in prepare
>   |     self.prepare_url(url, params)
>   |   File "/home/julia/eodag/venv/lib/python3.11/site-packages/requests/models.py", line 438, in prepare_url
>   |     raise MissingSchema(
>   | requests.exceptions.MissingSchema: Invali [...]

2025-02-10 14:09 UTC, alambare commented on eodag/resources/providers.yml
> +        <<: *day_month_year
I prefer we map the day. It is more aligned with the provider philosophy.

2025-02-11 11:24 UTC, jlahovnik requested changes
Now already the search is failing for wekeo_ecmwf:

`
{"errors":[{"provider":"wekeo_ecmwf","error":"RequestError","message":"Skipping error while searching for wekeo_ecmwf WekeoECMWFSearch instance","detail":" {\"status_code\":404,\"title\":\"Search Products\",\"detail\":\"Param 'dataset_id' not found\"}","status_code":404}]}
`

2025-03-04 14:36 UTC, sbrunato requested changes

2025-03-04 16:02 UTC, sbrunato approved these changes

2025-03-04 16:09 UTC, merged