Create tutorial about adding product types
CS-SI/eodag pull request #1434
Opened 2024-12-09 10:13 UTC by amarandon

2024-12-10 17:04 UTC, jlahovnik requested changes

2024-12-11 10:07 UTC, jlahovnik approved these changes

2024-12-18 16:34 UTC, sbrunato requested changes

2024-12-18 16:34 UTC, sbrunato commented on docs/add_product_type.rst
> +To add a new product type to EODag, you must add an entry to the file ``eodag/resources/product_types.yml``. Here is an example:
```suggestion
To add a new product type to EODAG, you must add an entry to the file ``eodag/resources/product_types.yml``. Here is an example:
```

2024-12-18 16:34 UTC, sbrunato commented on docs/add_product_type.rst
> +which the product will be referred to within EODag. Note the use of uppercase
```suggestion
which the product will be referred to within EODAG. Note the use of uppercase
```

2024-12-18 16:34 UTC, sbrunato commented on docs/add_product_type.rst
> +specified the instrument AWFI, the collection cbers4 and the processingLevel 2.
```suggestion
specified the instrument ``AWFI``, the collection ``cbers4`` and the processingLevel ``2``.
```

2024-12-18 16:34 UTC, sbrunato commented on docs/add_product_type.rst
> +be further processed by a metadata mapping:
```suggestion
that parameters have to be named following the common model used in EODAG (see `Parameters mapping <params_mapping.rst>`_). Part of the provider search metadata mapping can also be overridden per product-type, by adding a ``metadata_mapping`` section to the product type definition:
```

2025-01-03 08:05 UTC, sbrunato approved these changes

2025-01-03 08:06 UTC, merged