1385 update tutorials using eodag cube
CS-SI/eodag pull request #1436
Opened 2024-12-09 13:01 UTC by amarandon

Updated tuto_cds and tuto_ecmwf

Ref #1385

2024-12-09 13:29 UTC, jlahovnik requested changes
Please rebase the branch and re-check the querybles section of the cop_cds notebook afterwards!

2024-12-09 13:29 UTC, jlahovnik commented on docs/notebooks/tutos/tuto_ecmwf.ipynb
> +      "None product built EOProduct(id=TIGGE_CF_SFC_20211101_20211102_aa2ef8c02ebec293e6ab97e6c021689f74d52f8f, provider=ecmwf), \n",
The none here seems suspicious to me.

2024-12-09 13:29 UTC, jlahovnik commented on docs/notebooks/tutos/tuto_ecmwf.ipynb
> +      "None product built EOProduct(id=TIGGE_CF_SFC_20211101_20211102_77bafb137e4775c8b121b2a7886d7f5b0aa74454, provider=ecmwf), \n",
another None

2024-12-09 14:33 UTC, amarandon commented on docs/notebooks/tutos/tuto_ecmwf.ipynb
> +      "None product built EOProduct(id=TIGGE_CF_SFC_20211101_20211102_aa2ef8c02ebec293e6ab97e6c021689f74d52f8f, provider=ecmwf), \n",
Now it's a 1 again

2024-12-09 14:34 UTC, amarandon commented on docs/notebooks/tutos/tuto_ecmwf.ipynb
> +      "None product built EOProduct(id=TIGGE_CF_SFC_20211101_20211102_77bafb137e4775c8b121b2a7886d7f5b0aa74454, provider=ecmwf), \n",
Another 1 again :)

2024-12-09 15:07 UTC, jlahovnik requested changes
Please review search part in cop_cds tutorial: 

- request for variable temperature
- print in if is not executed but should be according to comment
- in first phrase two use case**s**

In ecmwf tutorial it still says "None product" after the first code block.

2024-12-09 16:01 UTC, amarandon commented
> Please review search part in cop_cds tutorial:
> 
>     * request for variable temperature
> 
>     * print in if is not executed but should be according to comment
> 
>     * in first phrase two use case**s**
> 
> 
> In ecmwf tutorial it still says "None product" after the first code block.

2024-12-09 16:03 UTC, amarandon commented
@jlahovnik I have pushed the requested changes to cop_cds tutorial.

Regarding ecmwf tutorial, I always get a `search_results.number_matched` with a None value, even if I reduce the search parameters to just the product name. Any idea what could be wrong?

2024-12-09 17:23 UTC, jlahovnik commented
> @jlahovnik I have pushed the requested changes to cop_cds tutorial.
> 
> Regarding ecmwf tutorial, I always get a `search_results.number_matched` with a None value, even if I reduce the search parameters to just the product name. Any idea what could be wrong?

Try to add count=True to the request.

2024-12-10 10:07 UTC, amarandon commented
> > @jlahovnik I have pushed the requested changes to cop_cds tutorial.
> > Regarding ecmwf tutorial, I always get a `search_results.number_matched` with a None value, even if I reduce the search parameters to just the product name. Any idea what could be wrong?
> 
> Try to add count=True to the request.

It worked, thank you!

2024-12-10 10:38 UTC, amarandon commented
@jlahovnik I also fixed the mars request in the ecmwf tutorial and a typo in providers.yml on the product origin

2024-12-10 11:04 UTC, jlahovnik approved these changes

2025-01-31 13:09 UTC, merged