docs: extract notebook about queryables
CS-SI/eodag pull request #1447
Opened 2024-12-13 13:56 UTC by amarandon

Address issue #1442

2024-12-16 13:24 UTC, jlahovnik requested changes
Maybe we could add a link to the queryables chapter somewhere in the search chapter (something like "if you want to know which query parameters you can use, you can check the queryables").

2024-12-16 13:24 UTC, jlahovnik commented on docs/notebooks/intro_notebooks.ipynb
> +    "* [Search](api_user_guide/5_queryables.ipynb)\n",
[Queryables]

2024-12-18 08:53 UTC, amarandon commented
> Maybe we could add a link to the queryables chapter somewhere in the search chapter (something like "if you want to know which query parameters you can use, you can check the queryables").

Done :heavy_check_mark:

2024-12-18 10:05 UTC, jlahovnik requested changes

2024-12-18 10:05 UTC, jlahovnik commented on docs/notebooks/api_user_guide/4_search.ipynb
> +    "The three search methods introduced below accept pretty much the same parameters, which are described further down the page. Note that if you wish to know which parameters are available to use i
There's something missing in this phrase.

2024-12-18 10:29 UTC, jlahovnik approved these changes

2025-01-08 18:28 UTC, sbrunato approved these changes

2025-01-08 18:29 UTC, merged