Recreate whoosh index when unsupported pickle protocol
CS-SI/eodag pull request #258
Opened 2021-04-21 21:19 UTC by maximlt

Fixes #240 

Thanks @sbrunato for the snippet!

I could test this by running eodag with python 3.8 first (which introduced a new pickle protocol) and then python 3.7, the error was properly caught and the index recreated.

2021-04-23 15:53 UTC, sbrunato requested changes

2021-04-23 15:53 UTC, sbrunato commented on eodag/api/core.py
>                  create_index = True
```suggestion
        try:
            create_index = not exists_in(index_dir)
            # check index version
            if not create_index:
                if self._product_types_index is None:
                    logger.debug("Opening product types index in %s", index_dir)
                    self._product_types_index = open_dir(index_dir)
                self.guess_product_type(eodagVersion=eodag_version)
        except NoMatchingProductType:
            create_index = True
        except ValueError as ve:
            # Whoosh uses pickle internally. New versions of Python sometimes introduce
            # a new pickle protocol (e.g. 3.4 -> 4, 3.8 -> 5), the new version not
            # being supported by previous versions of Python (e.g. Python 3.7 doesn't
            # support Protocol 5). In that case, we need to recreate the .index.
            if "unsupported pickle protocol" in str(ve):
                create_index = True
```

2021-04-23 15:53 UTC, sbrunato commented on eodag/api/core.py
> +                raise
```suggestion
            # Unexpected error
            else:
                logger.error(
                    "Error while building .index using whoosh, "
                    "please report this issue and try to delete %s manually",
                    index_dir,
                )
                raise
        finally:
            if create_index:
                shutil.rmtree(index_dir)
                logger.debug(
                    "Out-of-date product types index removed from %s", index_dir
                )
```

2021-04-23 18:34 UTC, maximlt commented
The tests failed after applying the suggestions, when the index was not yet created (first instantiation of EODataAccessGateway after installing for the first time) `shutil.rmtree(index_dir)` would raise an error.

I refactored the solution to make it more clear when an error is raised because of another pickle protocol used to create the index vs. an out-of-date index. I think it still preserves the special logic added in https://github.com/CS-SI/eodag/commit/d893dec5e2e76a3d4b502680e48ff2386edf5474 to handle the special NFS case.

I tried this code manually too.

2021-04-26 07:25 UTC, sbrunato approved these changes

2021-04-26 07:26 UTC, merged