feat: added SARA as a provider and respective S3 product definitions.
CS-SI/eodag pull request #578
Opened 2022-12-13 04:13 UTC by catchSheep

### Your checklist for this pull request
Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
    - As I've synced quite a few times without rebasing (whoops), it may be better to squash merge these changes.
- [x] Check your code additions will fail neither code linting checks nor unit test.
    - Currently passes all tests  the original passes except "tests/test_cli.py::TestEodagCli::test_eodag_cli_version", which may possibly just be on my end

### Description
Fixes/adds support for issues https://github.com/CS-SI/eodag/issues/575, https://github.com/CS-SI/eodag/issues/168 and https://github.com/CS-SI/eodag/issues/14. Adding  provider [SARA](https://copernicus.nci.org.au/sara.client/#/home) and SARA product types (eg S3 water products, SLSTR AOD & FRP, and synergy products).
The changes should only affect eodag/resources/providers.yml,  eodag/resources/product_types.yml, and update the test dictionaries with the newly added product types.

Also fixes  https://github.com/CS-SI/eodag/issues/577

2023-01-04 14:24 UTC, sbrunato requested changes

2023-01-04 15:04 UTC, sbrunato requested changes

2023-01-04 15:11 UTC, sbrunato requested changes
Hello @catchSheep , I wish you all the best for 2023! Sorry for the delay in reviewing this PR. 

Could you please rebase it on up-to-date `develop` branch in order to include #580 that fixes the failing test in github actions ?
Thanks

2023-01-05 05:53 UTC, catchSheep commented
> Hello @catchSheep , I wish you all the best for 2023! Sorry for the delay in reviewing this PR.
>
> Could you please rebase (or merge) it on up-to-date develop branch in order to include https://github.com/CS-SI/eodag/pull/580 that fixes the failing test in github actions ?
Thanks

No worries, happy new year to you too.

I had some issues merging the updates, so I re-wrote the history to the current CS-SI eodag develop branch, and git cherry-picked the relevant changes back in. It seems to be passing all relevant checks for python 3.9 & 3.10

2023-01-05 13:33 UTC, sbrunato requested changes

2023-01-05 13:33 UTC, sbrunato commented on eodag/resources/providers.yml
> +          cloudCover: '$.null'
```suggestion
```
restores https://github.com/CS-SI/eodag/pull/530

2023-01-05 13:33 UTC, sbrunato commented on eodag/resources/providers.yml
> +    api_endpoint: 'https://mundiwebservices.com/acdc/catalog/proxy/search/{collection}/opensearch'
```suggestion
    api_endpoint: 'https://{collection}.browse.catalog.mundiwebservices.com/opensearch'
```
restores https://github.com/CS-SI/eodag/pull/524

2023-01-05 13:33 UTC, sbrunato commented on eodag/resources/providers.yml
>      auth_error_code: 401
```suggestion
    auth_error_code: 401
    bucket_path_level: 0
```
restores https://github.com/CS-SI/eodag/pull/524

2023-01-05 15:12 UTC, sbrunato approved these changes

2023-01-05 15:12 UTC, merged