Configure product split params wekeo
CS-SI/eodag pull request #889
Opened 2023-10-17 15:39 UTC by jlahovnik

- product splitting configurations for remaining wekeo ECMWF product types
- splitting by additional parameters (e.g. leadtime hour) is introduced

2023-11-22 15:09 UTC, sbrunato requested changes

2023-11-22 15:09 UTC, sbrunato commented on eodag/api/product/request_splitter.py
- please add logger and use it instead of `print`
- use USER_AGENT in requests headers
- handle requests errors (`raise_for_status` usage and exception interception)

2023-11-22 15:09 UTC, sbrunato commented on eodag/rest/utils.py
> +    print("utils", variable)
please do not use `print()`

2023-11-22 15:43 UTC, sbrunato requested changes
please add a new `cached_requests_get` in `eodag.utils` and use it in `request_splitter` to speedup multiple requests to the same url

2023-11-24 07:52 UTC, jlahovnik commented on eodag/api/product/request_splitter.py
done

2023-11-24 07:52 UTC, jlahovnik commented on eodag/rest/utils.py
> +    print("utils", variable)
removed

2023-11-24 10:42 UTC, sbrunato commented
> please add a new `cached_requests_get` in `eodag.utils` and use it in `request_splitter` to speedup multiple requests to the same url

done

2023-11-24 16:31 UTC, sbrunato requested changes
Please
- [x] rename `product_data` to `product_type_conf`
- [x] rename `provider_product` to `provider_product_type`
- [ ] replace hard-coded `"dataset"` with a new provider setting: `<provider>.search.metadata_mapping.providerProductType: $.dataset`
- [x] rename `constraints_param` setting to `constraints_entry`
- [ ] do not use any `server_mode` parameter, and directly use `assets` instead of `downloadLinks` in server mode
- [ ] http://127.0.0.1:5000/catalogs/CAMS_GACF_MR/year/2021/items responds fast but http://127.0.0.1:5000/catalogs/CAMS_GACF_MR/items hangs forever 
- [x] use `HTTP_REQ_TIMEOUT` for constraints request
- [ ] in server mode, use `{item}/download/{variable}` pattern for assets `href`

2023-11-30 11:14 UTC, jlahovnik commented
> Please
> 
>     * [x]  rename `product_data` to `product_type_conf`
> 
>     * [x]  rename `provider_product` to `provider_product_type`
> 
>     * [ ]  replace hard-coded `"dataset"` with a new provider setting: `<provider>.search.metadata_mapping.providerProductType: $.dataset`
> 
>     * [x]  rename `constraints_param` setting to `constraints_entry`
> 
>     * [ ]  do not use any `server_mode` parameter, and directly use `assets` instead of `downloadLinks` in server mode
> 
>     * [ ]  http://127.0.0.1:5000/catalogs/CAMS_GACF_MR/year/2021/items responds fast but http://127.0.0.1:5000/catalogs/CAMS_GACF_MR/items hangs forever
> 
>     * [x]  use `HTTP_REQ_TIMEOUT` for constraints request
> 
>     * [ ]  in server mode, use `{item}/download/{variable}` pattern for assets `href`

renaming of variables done, timeout added
I don't understand the 3rd point. Where should that change be done?

2023-12-01 08:14 UTC, jlahovnik commented
issue with http://127.0.0.1:5000/catalogs/CAMS_GACF_MR/items request is fixed

2025-02-07 18:47 UTC, closed without merging