feat: add cop(ads, cds) product types
CS-SI/eodag pull request #898
Opened 2023-10-24 14:38 UTC by bjgiraudon

### Description
This MR adds new product types and `cop` metadata to `cop_cds` and `cop_ads` providers.

This MR fixes the issue #855

2023-10-27 07:49 UTC, alambare-csgroup commented
This MR also partially cover [#509](https://github.com/CS-SI/eodag/issues/509)

2023-11-17 13:58 UTC, alambare-csgroup commented
Windows tests to fix

2023-12-01 10:26 UTC, sbrunato requested changes

2023-12-01 10:26 UTC, sbrunato commented on eodag/resources/providers.yml
> +        - '$.date'
I am not sure the `date` field is needed : dates are already usable through `start` and `end` parameters using these settings:
```yml
startTimeFromAscendingNode: '{$.startTimeFromAscendingNode#to_iso_date}'
completionTimeFromAscendingNode:
  - 'date={startTimeFromAscendingNode#to_iso_date}/{completionTimeFromAscendingNode#to_iso_date(-1,)}'
  - '{$.completionTimeFromAscendingNode#to_iso_date}'
```

2023-12-06 08:50 UTC, sbrunato requested changes

2023-12-13 09:49 UTC, sbrunato approved these changes

2023-12-13 09:50 UTC, merged