850 avoid search by id before every server mode download
CS-SI/eodag pull request #916
Opened 2023-11-08 14:28 UTC by jlahovnik

- used mechanism created for wekeo where download info is stored in the search plugin
- storing of download info added for data request search and query string search (stac search and post json search inherit from query string search)
- if download is attempted for product where id is not in download info and search by id is available for provider and product type, it will be executed; if search by id is not possible an error will be raised to do a search

2023-12-06 15:46 UTC, jlahovnik commented
updated based on input from @alambare-csgroup

2023-12-21 08:00 UTC, sbrunato requested changes

2023-12-21 08:00 UTC, sbrunato commented on eodag/api/core.py
> +        self.download_info = {}
Please store full SearchResult objects in a `_search_results_cache = collections.dequeue()` having `maxlen` default to 100 (stored in a new constant) and customizable using an environment variable like `EODAG_SEARCH_RESULTS_CACHE_MAXLEN`.

Please also put `_search_results_cache` in `rest.utils` as it only concerns server-mode downloads.

To find a matching product, loop over the cache starting with the most recent result. (check at first only provider and product type of the first product of each search result)

2024-02-06 11:47 UTC, closed without merging

2024-02-06 11:48 UTC, jlahovnik commented
closed because change requests were implemented on new branch -> new PR: [https://github.com/CS-SI/eodag/pull/1012](https://github.com/CS-SI/eodag/pull/1012)