feat: implement new core method get_queryables
CS-SI/eodag pull request #917
Opened 2023-11-08 16:28 UTC by dalpasso

Implements a new core method `def get_queryables(provider=None, product_type=None) -> List[str]`:

- If no `provider` and no `product_type` are passed, then returns default search method queryable parameters: `["productType", "start", "end", "geom", "locations", "id"]`
- If a `provider` is passed (but no `product_type`), then returns its queryable parameters from provider's config
- If a `product_type` is passed (but no `provider`), then returns the union of the queryable parameters from all providers supporting the given `product_type`
- If both a `product_type` and a `provider` are passed, then returns the queryable parameters from provider's config and the queryable parameters for that product type

2023-11-14 10:51 UTC, sbrunato requested changes
- if given provider is not found, please raise `UnsupportedProvider()`
- if given product_type is not found, please raise `UnsupportedProductType()`
- if product type is given, but no provider, only return preferred provider queryables instead of the union of all possibles

2023-11-14 10:51 UTC, sbrunato commented on eodag/api/core.py
> +            providers = self._plugins_manager.providers_config.values()
```suggestion
        if provider in self.providers_config:
            providers = [self.providers_config[provider]]
        else:
            providers = self.providers_config.values()
```

2023-11-14 10:51 UTC, sbrunato commented on eodag/api/core.py
> +                plugin_config = provider_config.api
```suggestion
            elif hasattr(provider_config, "api"):
                plugin_config = provider_config.api
            else:
                continue
```

2023-11-15 15:05 UTC, dalpasso commented
Changed the implementation:

- added a default list of queryables to all the providers
- when `product_type` is given, but no `provider`, then return the intersection of the queryables of all the providers supporting it

2023-12-05 15:09 UTC, sbrunato requested changes

2023-12-05 15:09 UTC, sbrunato commented on eodag/rest/utils.py
> +    if key in OSEO_METADATA_MAPPING:
use `get_criterias_from_metadata_mapping(stac_provider_metadata_mapping, arguments)` for that

2023-12-06 16:37 UTC, merged